config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users
  resource :session
  resource :account

  get "about", to: "pages#about"
  get "terms", to: "pages#about"

  root "reviews#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :review
  belongs_to :user

  validates :body, presence: true
end

app/models/page.rb
class Page < ApplicationRecord

  validates :url, uniqueness: true

  mount_uploader :image, ContentImageUploader
end

app/models/review.rb
class Review < ApplicationRecord

  has_many :comments
  has_many :bookmarks
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :body, length: { minimum: 10 }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :restaurant, presence: true
  validates :address, presence: true


  def to_param
    id.to_s + "-" + title.parameterize
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :comments
  has_many :bookmarks

  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :check_login

  def edit
  end

  def show
    redirect_to edit_account_path
  end

  def update
    if @current_user.update(form_params)
      flash[:success] = "Account Updated"
    end
    render "edit"
  end

  def form_params
    params.require(:user).permit(:username, :email)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @comment = @review.comments.new(params.require(:comment).permit(:body))
    @comment.user = @current_user
    @comment.save
    flash[:success] = "Comment Posted"
    redirect_to review_path(@review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @content = Page.find_by(url: "about")
  end

  def terms
    @content = Page.find_by(url: "terms")
  end

  def home
    @content = Page.find_by(url: "home")
    @highly_rated_reviews = Review.where("score >= 8")
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :check_login, except: [:index, :show]

  def index
    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]

    @reviews = Review.all

    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    if @location.present?
      @reviews = @reviews.near(@location)
    end
  end

  def new
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(form_params)
    @review.user = @current_user

    if @review.save
      flash[:success] = "Review Posted"
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.user == @current_user
      @review.destroy
    end
    redirect_to root_path
  end

  def edit
    @review = Review.find(params[:id])
    if @review.user != @current_user
      redirect_to root_path
    elseif @review.created_at < 1.hour.ago
      redirect_to review_path(@review)
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    else
      if @review.update(form_params)
        redirect_to review_path(@review)
      else
        render "edit"
      end
    end
  end

  def form_params
    params.require(:review).permit(:title, :body, :score, :restaurant, :photo, :ambiance, :phone_number, :price, :cuisine, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #login form
  end

  def create
    @form_data = params.require(:session)
    @username = @form_data[:username]
    @password = @form_data[:password]

    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end

  end

  def destroy
    #logout
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(form_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to HYPE"
      redirect_to users_path
    else
      render "new"
    end
  end

  def form_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> | HYPE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav>
        <h1>
          <%= link_to root_path do %>
           <%= image_tag "HYPE.svg" %>
          <% end %>
        </h1>
      </nav>

      <form action="/">
        <input type="text" name="location" placeholder="search by city" value="<%= @location %>">

        <input type="hidden" name="price" value="<% @price %>">
        <input type="hidden" name="cuisine" value="<% @cuisine %>">
      </form>

      <nav>
        <% if is_logged_in? %>

          <%= @current_user.username %> |

          <% if @current_user.is_admin? %>
            <%= link_to "admin", admin_root_path %> |
          <% end %>

          <%= link_to "add review", new_review_path %> |
          <%= link_to "edit", edit_account_path %> |
          <%= link_to "logout", session_path, method: :delete %>

        <% else %>

          <%= link_to "sign up", new_user_path %> |
          <%= link_to "login", new_session_path %>
        <% end %>
      </nav>

    </header>

    <% if flash[:success].present? %>
      <div class="message">
        <%= flash[:success] %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer>
      HYPE Copyright 2019 | <%= link_to "about", about_path %> | <%= link_to "terms", terms_path %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<%= image_tag(@content.image_url.to_s) %>

<h1><%= @content.title %></h1>

<%= simple_format @content.body %>

app/views/pages/terms.html.erb
<%= image_tag(@content.image_url.to_s) %>

<h1><%= @content.title %></h1>

<%= simple_format @content.body %>