config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users
  resource :session
  resource :account

  get "about", to: "pages#about"
  get "terms", to: "pages#about"

  root "reviews#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :review
  belongs_to :user

  validates :body, presence: true
end

app/models/page.rb
class Page < ApplicationRecord

  validates :url, uniqueness: true

  mount_uploader :image, ContentImageUploader
end

app/models/review.rb
class Review < ApplicationRecord

  has_many :comments
  has_many :bookmarks
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :body, length: { minimum: 10 }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :restaurant, presence: true
  validates :address, presence: true


  def to_param
    id.to_s + "-" + title.parameterize
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :comments
  has_many :bookmarks

  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def to_param
    username
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :check_login

  def edit
  end

  def show
    redirect_to edit_account_path
  end

  def update
    if @current_user.update(form_params)
      flash[:success] = "Account Updated"
    end
    render "edit"
  end

  def form_params
    params.require(:user).permit(:username, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :find_current_user
  helper_method :is_logged_in?

  def find_current_user
    if is_logged_in?
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def check_login
    unless is_logged_in?
      redirect_to new_session_path
    end
  end

  def is_logged_in?
    session[:user_id].present?
  end

  def check_admin
    @current_user = find_current_user

    unless @current_user.present? and @current_user.is_admin?
      redirect_to root_path
    end
  end

  def find_admin_user
    @current_user = find_current_user

    if @current_user.present? and @current_user.is_admin?
      @current_user
    else
      nil
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :check_login

  def create
    @review = Review.find(params[:review_id])
    @bookmark = @review.bookmarks.new
    @bookmark.user = @current_user
    @bookmark.save
    redirect_to review_path(@review)
  end

  def destroy
    @review = Review.find(params[:review_id])
    @review.bookmarks.where(user: @current_user).delete_all
    redirect_to review_path(@review)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @comment = @review.comments.new(params.require(:comment).permit(:body))
    @comment.user = @current_user
    @comment.save
    flash[:success] = "Comment Posted"
    redirect_to review_path(@review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @content = Page.find_by(url: "about")
  end

  def terms
    @content = Page.find_by(url: "terms")
  end

  def home
    @content = Page.find_by(url: "home")
    @highly_rated_reviews = Review.where("score >= 8")
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :check_login, except: [:index, :show]

  def index
    @price = params[:price]
    @cuisine = params[:cuisine]
    @location = params[:location]

    @reviews = Review.all

    if @price.present?
      @reviews = @reviews.where(price: @price)
    end

    if @cuisine.present?
      @reviews = @reviews.where(cuisine: @cuisine)
    end

    if @location.present?
      @reviews = @reviews.near(@location)
    end
  end

  def new
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(form_params)
    @review.user = @current_user

    if @review.save
      flash[:success] = "Review Posted"
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.user == @current_user
      @review.destroy
    end
    redirect_to root_path
  end

  def edit
    @review = Review.find(params[:id])
    if @review.user != @current_user
      redirect_to root_path
    elseif @review.created_at < 1.hour.ago
      redirect_to review_path(@review)
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.user != @current_user
      redirect_to root_path
    else
      if @review.update(form_params)
        redirect_to review_path(@review)
      else
        render "edit"
      end
    end
  end

  def form_params
    params.require(:review).permit(:title, :body, :score, :restaurant, :photo, :ambiance, :phone_number, :price, :cuisine, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #login form
  end

  def create
    @form_data = params.require(:session)
    @username = @form_data[:username]
    @password = @form_data[:password]

    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end

  end

  def destroy
    #logout
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(form_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to HYPE"
      redirect_to users_path
    else
      render "new"
    end
  end

  def form_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>


<%= simple_form_for @current_user, url: account_path do |f| %>
  <%= f.input :username %>
  <%= f.input :email %>

  <%= f.button :submit, "confirm" %>

<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>

  <% if @review.errors.any? %>
    <div class="errors">
      <% @review.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <p>
    <%= f.input :title %>
    <%= f.input :restaurant %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.input :phone_number %>
    <%= f.input :price %>
    <%= f.input :ambiance %>
    <%= f.input :cuisine %>
    <%= f.input :body %>
    <%= f.input :score %>
    <%= f.button :submit, "add review" %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Home" %>

<nav class="filters">
  <%= active_link_to "all restaurants", root_path, active: { price: nil, cuisine: nil, location: nil } %>

  <%= active_link_to "£", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 } %>
  <%= active_link_to "££", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 }  %>
  <%= active_link_to "£££", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 }  %>

  <%= active_link_to "english", root_path(cuisine: "English", price: @price, location: @location), active: { cuisine: "English" } %>
  <%= active_link_to "indian", root_path(cuisine: "Indian", price: @price, location: @location), active: { cuisine: "Indian" } %>
  <%= active_link_to "thai", root_path(cuisine: "Thai", price: @price, location: @location), active: { cuisine: "Thai" } %>
  <%= active_link_to "mexican", root_path(cuisine: "Mexican", price: @price, location: @location), active: { cuisine: "Mexican" } %>
  <%= active_link_to "italian", root_path(cuisine: "Italian", price: @price, location: @location), active: { cuisine: "Italian" } %>

</nav>


<% @reviews.each do |review| %>
  <div class="review">
    <%= link_to review_path(review) do %>

      <h2><%= review.title %></h2>
      <p>
        <%= review.restaurant %> |
        <%= review.cuisine %>
      </p>
      <%= image_tag(review.photo_url(:thumb).to_s) %>
      <p><%= pluralize review.comments.count, "comment" %></p>

    <% end %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "add review" %>

<h3>add a review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2>Restaurant | <%= @review.restaurant %></h2>

<%= image_tag(@review.photo_url(:medium).to_s) %>

<div class="user">
  Posted by

  <% if @review.user.present? %>
    <%= @review.user.username %> 
  <% else %>
    anonymous
  <% end %>
</div>

<% if is_logged_in? %>
  <p>
    <% if @review.bookmarks.where(user: @current_user).any? %>
      <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>
    <% else %>
      <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
    <% end %>
  </p>
<% end %>

<h3>Bookmarked by</h3>

<ul>
  <% @review.bookmarks.each do |bookmark| %>
    <li><%= bookmark.user.username %></li>
  <% end %>
</ul>

<% if @review.phone_number.present? %>
  <h3>Tel | <%= @review.phone_number %></h3>
<% end %>

<% if @review.ambiance.present? %>
  <h3>Ambiance | <%= @review.ambiance %></h3>
<% end %>

<% if @review.price.present? %>
    <h3>Price | £<%= @review.price %></h3>
<% end %>

<div class="score">
  Score | <%= @review.score %> / 10
</div>

<% if @review.cuisine.present? %>
  <div class="cuisine">
    Cuisine | <%= @review.cuisine %>
  </div>
<% end %>

<div class="body">
  <%= simple_format @review.body %>
</div>

<% if @review.user == @current_user %>
  <div class="actions">
    <% if @review.created_at > 1.hour.ago %>
      <%= link_to "edit", edit_review_path(@review) %> |
    <% end %>
    <%= link_to "delete", review_path(@review), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<h3>Comments</h3>

<% @review.comments.order("created_at desc").each do |comment| %>
  <div class="comment">
    <%= simple_format comment.body %>

    <p class="posted">
      Posted by
        <% if comment.user.present? %>
          <%= link_to comment.user.username, user_path(comment.user) %>
        <% else %>
          anonymous
        <% end %>
    </p>

    <p class="posted"><%= time_ago_in_words comment.created_at %> ago</p>
  </div>
<% end %>

<h3>add comment</h3>
<%= simple_form_for [@review, Comment.new] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, "add comment" %>
<% end %>

app/views/users/index.html.erb
<h1>Users Online</h1>

<% @users.each do |user| %>
  <p>
    <%= user.username %> // <%= user.email %>
  </p>
<% end %>

app/views/users/new.html.erb
<h2>Sign up to HYPE</h2>

<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: "Confirm password" %>
  <%= f.button :submit, "sign up" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<p>
  Email | <%= @user.email %>
</p>